spring.application.name=retoback

## base de datos MySQL
spring.datasource.url=jdbc:mysql://127.0.0.1:3307/reto_db
spring.datasource.username=reto_edit
spring.datasource.password=RETO1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#sawagger
# http://localhost:8080/swagger-ui.html


# Evitar errores de definición de beans duplicados (por si acaso)
spring.main.allow-bean-definition-overriding=true
