spring.application.name=retoback

# base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/reto
spring.datasource.username=root
spring.datasource.password=santoysena
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#sawagger
# http://localhost:8080/swagger-ui.html
