spring.application.name=retoback

# base de datos PostgreSQL
# Conexión al servidor de Álvaro (Túnel SSH activo en tu PC)
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/reto_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=reto_edit
spring.datasource.password=RETO1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#sawagger
# http://localhost:8080/swagger-ui.html
